# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://dongrenwen.github.io
date_format: "ordinal"
title: 董仁文的博客
subtitle: "建设中，敬请期待"
description: "董仁文的个人博客"
keywords: 董仁文, Renwen Dong, dongrenwen
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Renwen Dong
organization: dongrenwen.github.io
organization_url: https://dongrenwen.github.io
github_username: dongrenwen
location: Changchun, China
email: dongrenwen@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: dongrenwen/dongrenwen.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: dongrenwen
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: dongrenwen
    repo: blog-comments
    oauth:
        client_id: 714700c9625eb94e66af
        client_secret: 78639b30e3e03d1d73a0495ab9835d9699b39169
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: dongrenwen
    repo: blog-comments
    clientID: 714700c9625eb94e66af
    clientSecret: 78639b30e3e03d1d73a0495ab9835d9699b39169
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-118257699-1
